require('mv.options')
require('mv.plugins')

require('mv.mappings')
require('mv.colorscheme')
require('mv.trimwhite')
require('mv.lualine')
require('mv.telescope')
require('mv.compe')
require('mv.lspkind')
require('mv.nvim-tree')
require('mv.nvim-autopairs')

require('mv.treesitter')
require('mv.lsp')
require('mv.lsp.servers')
require('mv.lsp.efm')
require('mv.lspsaga')

require('mv.rust')
require('mv.rusttools')
require('mv.dap')
require('mv.dap.lldb')
require('mv.dapui')
